// AN3S Tailwind preset: the palette, fonts, radii and shadows are only design-system tokens.
// Generated by tools/export.mjs from project/tokens.json. Do not edit: change the design system, then re-export.
/** @type {import('tailwindcss').Config} */
export default {
  "theme": {
    "colors": {
      "transparent": "transparent",
      "current": "currentColor",
      "inherit": "inherit",
      "black": "hsl(var(--void-hsl) / <alpha-value>)",
      "white": "hsl(var(--ink-hsl) / <alpha-value>)",
      "void": "hsl(var(--void-hsl) / <alpha-value>)",
      "deep-space": "hsl(var(--deep-space-hsl) / <alpha-value>)",
      "panel": "hsl(var(--panel-hsl) / <alpha-value>)",
      "nebula": "hsl(var(--nebula-hsl) / <alpha-value>)",
      "line": "hsl(var(--line-channels) / calc(<alpha-value> * var(--line-alpha)))",
      "line-strong": "hsl(var(--line-strong-channels) / calc(<alpha-value> * var(--line-strong-alpha)))",
      "ink": "hsl(var(--ink-hsl) / <alpha-value>)",
      "ink-soft": "hsl(var(--ink-soft-hsl) / <alpha-value>)",
      "ink-muted": "hsl(var(--ink-muted-hsl) / <alpha-value>)",
      "pink": "hsl(var(--pink-hsl) / <alpha-value>)",
      "violet": "hsl(var(--violet-hsl) / <alpha-value>)",
      "blue": "hsl(var(--blue-hsl) / <alpha-value>)",
      "cyan": "hsl(var(--cyan-hsl) / <alpha-value>)",
      "pink-glow": "hsl(var(--pink-glow-hsl) / <alpha-value>)",
      "violet-glow": "hsl(var(--violet-glow-hsl) / <alpha-value>)",
      "cyan-glow": "hsl(var(--cyan-glow-hsl) / <alpha-value>)",
      "on-glow": "hsl(var(--on-glow-hsl) / <alpha-value>)",
      "link": "hsl(var(--link-hsl) / <alpha-value>)",
      "focus": "hsl(var(--focus-hsl) / <alpha-value>)",
      "danger": "hsl(var(--danger-hsl) / <alpha-value>)",
      "on-danger": "hsl(var(--on-danger-hsl) / <alpha-value>)",
      "success": {
        "DEFAULT": "hsl(var(--success-hsl) / <alpha-value>)",
        "foreground": "hsl(var(--on-success-hsl) / <alpha-value>)"
      },
      "on-success": "hsl(var(--on-success-hsl) / <alpha-value>)",
      "border": "hsl(var(--border-channels) / calc(<alpha-value> * var(--border-alpha)))",
      "input": "hsl(var(--input-channels) / calc(<alpha-value> * var(--input-alpha)))",
      "ring": "hsl(var(--ring) / <alpha-value>)",
      "background": "hsl(var(--background) / <alpha-value>)",
      "foreground": "hsl(var(--foreground) / <alpha-value>)",
      "primary": {
        "DEFAULT": "hsl(var(--primary) / <alpha-value>)",
        "foreground": "hsl(var(--primary-foreground) / <alpha-value>)"
      },
      "secondary": {
        "DEFAULT": "hsl(var(--secondary) / <alpha-value>)",
        "foreground": "hsl(var(--secondary-foreground) / <alpha-value>)"
      },
      "destructive": {
        "DEFAULT": "hsl(var(--destructive) / <alpha-value>)",
        "foreground": "hsl(var(--destructive-foreground) / <alpha-value>)"
      },
      "muted": {
        "DEFAULT": "hsl(var(--muted) / <alpha-value>)",
        "foreground": "hsl(var(--muted-foreground) / <alpha-value>)"
      },
      "accent": {
        "DEFAULT": "hsl(var(--accent) / <alpha-value>)",
        "foreground": "hsl(var(--accent-foreground) / <alpha-value>)"
      },
      "popover": {
        "DEFAULT": "hsl(var(--popover) / <alpha-value>)",
        "foreground": "hsl(var(--popover-foreground) / <alpha-value>)"
      },
      "card": {
        "DEFAULT": "hsl(var(--card) / <alpha-value>)",
        "foreground": "hsl(var(--card-foreground) / <alpha-value>)"
      },
      "chart": {
        "1": "hsl(var(--chart-1) / <alpha-value>)",
        "2": "hsl(var(--chart-2) / <alpha-value>)",
        "3": "hsl(var(--chart-3) / <alpha-value>)",
        "4": "hsl(var(--chart-4) / <alpha-value>)",
        "5": "hsl(var(--chart-5) / <alpha-value>)"
      },
      "sidebar": {
        "DEFAULT": "hsl(var(--sidebar-background) / <alpha-value>)",
        "foreground": "hsl(var(--sidebar-foreground) / <alpha-value>)",
        "primary": "hsl(var(--sidebar-primary) / <alpha-value>)",
        "primary-foreground": "hsl(var(--sidebar-primary-foreground) / <alpha-value>)",
        "accent": "hsl(var(--sidebar-accent) / <alpha-value>)",
        "accent-foreground": "hsl(var(--sidebar-accent-foreground) / <alpha-value>)",
        "border": "hsl(var(--sidebar-border-channels) / calc(<alpha-value> * var(--sidebar-border-alpha)))",
        "ring": "hsl(var(--sidebar-ring) / <alpha-value>)"
      }
    },
    "fontFamily": {
      "sans": "var(--font-sans)",
      "mono": "var(--font-mono)",
      "heading": "var(--font-sans)"
    },
    "borderRadius": {
      "none": "0",
      "sm": "var(--radius-sm)",
      "DEFAULT": "var(--radius-sm)",
      "md": "var(--radius-md)",
      "lg": "var(--radius-lg)",
      "xl": "var(--radius-lg)",
      "2xl": "var(--radius-lg)",
      "3xl": "var(--radius-lg)",
      "full": "var(--radius-full)"
    },
    "boxShadow": {
      "none": "none",
      "sm": "none",
      "DEFAULT": "none",
      "md": "none",
      "lg": "none",
      "xl": "none",
      "2xl": "none",
      "inner": "none",
      "glow-pink": "var(--glow-pink)",
      "glow-blue": "var(--glow-blue)",
      "glow-cyan": "var(--glow-cyan)",
      "focus-ring": "var(--focus-ring)"
    },
    "extend": {
      "backgroundImage": {
        "gradient-glow": "var(--gradient-glow)",
        "gradient-neon": "var(--gradient-neon)",
        "gradient-space": "var(--gradient-space)"
      },
      "fontSize": {
        "name-light": [
          "56px",
          {
            "lineHeight": "60px",
            "fontWeight": "300",
            "letterSpacing": "0.04em"
          }
        ],
        "name-bold": [
          "56px",
          {
            "lineHeight": "60px",
            "fontWeight": "800",
            "letterSpacing": "0.02em"
          }
        ],
        "tagline": [
          "20px",
          {
            "lineHeight": "28px",
            "fontWeight": "600",
            "letterSpacing": "0.32em"
          }
        ],
        "statement": [
          "24px",
          {
            "lineHeight": "34px",
            "fontWeight": "400",
            "letterSpacing": "0.14em"
          }
        ],
        "label": [
          "15px",
          {
            "lineHeight": "20px",
            "fontWeight": "600",
            "letterSpacing": "0.22em"
          }
        ],
        "eyebrow": [
          "13px",
          {
            "lineHeight": "16px",
            "fontWeight": "500",
            "letterSpacing": "0.24em"
          }
        ],
        "service": [
          "14px",
          {
            "lineHeight": "18px",
            "fontWeight": "500",
            "letterSpacing": "0.03em"
          }
        ],
        "action": [
          "14px",
          {
            "lineHeight": "20px",
            "fontWeight": "700",
            "letterSpacing": "0.16em"
          }
        ],
        "heading": [
          "28px",
          {
            "lineHeight": "36px",
            "fontWeight": "700",
            "letterSpacing": "0.01em"
          }
        ],
        "body": [
          "16px",
          {
            "lineHeight": "26px",
            "fontWeight": "400"
          }
        ],
        "caption": [
          "13px",
          {
            "lineHeight": "18px",
            "fontWeight": "500",
            "letterSpacing": "0.02em"
          }
        ],
        "code": [
          "14px",
          {
            "lineHeight": "22px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "space-1": "var(--space-1)",
        "space-2": "var(--space-2)",
        "space-3": "var(--space-3)",
        "space-4": "var(--space-4)",
        "space-5": "var(--space-5)",
        "space-6": "var(--space-6)",
        "space-7": "var(--space-7)",
        "space-8": "var(--space-8)"
      },
      "maxWidth": {
        "measure": "var(--measure)"
      },
      "minHeight": {
        "control": "var(--control)"
      },
      "height": {
        "control": "var(--control)",
        "icon-tile": "var(--icon-tile)",
        "icon-inline": "var(--icon-inline)"
      },
      "width": {
        "icon-tile": "var(--icon-tile)",
        "icon-inline": "var(--icon-inline)"
      }
    }
  }
};
