// AN3S design tokens as typed values, for code that can't read CSS custom properties (charts, canvas).
// Colours are resolved to hex (aliases followed). Generated by tools/export.mjs from project/tokens.json. Do not edit: change the design system, then re-export.

export const color = {
  "void": "#000000",
  "deep-space": "#03041d",
  "panel": "#080a24",
  "nebula": "#250533",
  "line": "#d0ccd852",
  "line-strong": "#b2b1b68c",
  "ink": "#ffffff",
  "ink-soft": "#e3e5e5",
  "ink-muted": "#b2b1b6",
  "pink": "#fb49b6",
  "violet": "#9020ca",
  "blue": "#2476f0",
  "cyan": "#48e1fd",
  "pink-glow": "#f589d7",
  "violet-glow": "#d395f0",
  "cyan-glow": "#85f5fd",
  "on-glow": "#03041d",
  "link": "#85f5fd",
  "focus": "#48e1fd",
  "danger": "#f2564a",
  "on-danger": "#03041d",
  "success": "#8af5b6",
  "on-success": "#03041d"
} as const;

export const shadow = {
  "glow-pink": "0 0 14px #fb49b659, 0 0 40px #fb49b626",
  "glow-blue": "0 0 14px #2476f066, 0 0 40px #2476f02e",
  "glow-cyan": "0 0 12px #48e1fd66, 0 0 32px #48e1fd26",
  "focus-ring": "0 0 0 2px #03041d, 0 0 0 4px #48e1fd"
} as const;

export const gradient = {
  "gradient-glow": "linear-gradient(90deg, #f589d7 0%, #d395f0 50%, #85f5fd 100%)",
  "gradient-neon": "linear-gradient(90deg, #fb49b6 0%, #9020ca 50%, #2476f0 100%)",
  "gradient-space": "radial-gradient(120% 90% at 15% 110%, #250533 0%, #03041d 55%, #000000 100%)"
} as const;

export const space = {
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-5": "24px",
  "space-6": "32px",
  "space-7": "48px",
  "space-8": "72px"
} as const;

export const radius = {
  "radius-sm": "6px",
  "radius-md": "10px",
  "radius-lg": "18px",
  "radius-full": "9999px"
} as const;

export const size = {
  "control": "44px",
  "icon-tile": "48px",
  "icon-inline": "20px",
  "measure": "68ch"
} as const;

export const font = {
  "sans": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
  "mono": "ui-monospace, \"Cascadia Code\", \"SF Mono\", Menlo, Consolas, monospace"
} as const;

export const typeStyle = {
  "name-light": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "56px",
    "lineHeight": "60px",
    "fontWeight": 300,
    "letterSpacing": "0.04em"
  },
  "name-bold": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "56px",
    "lineHeight": "60px",
    "fontWeight": 800,
    "letterSpacing": "0.02em"
  },
  "tagline": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "20px",
    "lineHeight": "28px",
    "fontWeight": 600,
    "letterSpacing": "0.32em"
  },
  "statement": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "24px",
    "lineHeight": "34px",
    "fontWeight": 400,
    "letterSpacing": "0.14em"
  },
  "label": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "15px",
    "lineHeight": "20px",
    "fontWeight": 600,
    "letterSpacing": "0.22em"
  },
  "eyebrow": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "13px",
    "lineHeight": "16px",
    "fontWeight": 500,
    "letterSpacing": "0.24em"
  },
  "service": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "14px",
    "lineHeight": "18px",
    "fontWeight": 500,
    "letterSpacing": "0.03em"
  },
  "action": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "14px",
    "lineHeight": "20px",
    "fontWeight": 700,
    "letterSpacing": "0.16em"
  },
  "heading": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "28px",
    "lineHeight": "36px",
    "fontWeight": 700,
    "letterSpacing": "0.01em"
  },
  "body": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "16px",
    "lineHeight": "26px",
    "fontWeight": 400
  },
  "caption": {
    "fontFamily": "\"Montserrat\", \"Segoe UI\", system-ui, sans-serif",
    "fontSize": "13px",
    "lineHeight": "18px",
    "fontWeight": 500,
    "letterSpacing": "0.02em"
  },
  "code": {
    "fontFamily": "ui-monospace, \"Cascadia Code\", \"SF Mono\", Menlo, Consolas, monospace",
    "fontSize": "14px",
    "lineHeight": "22px",
    "fontWeight": 400
  }
} as const;

export const googleFontsHref = "https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap";

export type ColorToken = keyof typeof color;
export type TypeStyle = keyof typeof typeStyle;
